<?php
use \Framework\Tools\Helper\RoutesHelper;
use \Framework\Tools\Helper\PathHelper;
use \PL\Helper\User\UserHelper;
?>

<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<title>FamilyHub</title>
	<link rel="stylesheet" type="text/css" href="<?= PathHelper::GetCssStyleFilePath() ?>">
	<link rel="stylesheet" href="https://use.fontawesome.com/releases/v6.4.0/css/all.css" crossorigin="anonymous">
	<link href="https://fonts.googleapis.com/css?family=Open+Sans:400,700|Roboto:400,700" rel="stylesheet">
	<script type="text/javascript" src="<?= PathHelper::GetJsFilePath('jquery/jquery-3.3.1.min.js') ?>"></script>
</head>
<body>
	<header class="l-header header">
		<nav class="nav">
			<section class="nav__brand">
				<a class="nav__brand__logo" href="<?= RoutesHelper::Path("DisplayHome"); ?>">FamilyHub</a>
				<span class="nav__brand__complement">Le hub pour toute la famille</span>
			</section>
			<section class="nav__menu">
				<a href="<?= RoutesHelper::Path("DisplayHome"); ?>" class="nav__menu__item--start">Les listes</a>
				<!-- <a href="<?= RoutesHelper::Path("DisplayHome"); ?>" class="nav__menu__item--spending">Les repas</a>
				<a href="<?= RoutesHelper::Path("DisplayHome"); ?>" class="nav__menu__item--spending">Les tâches</a>
				<a href="<?= RoutesHelper::Path("DisplayHome"); ?>" class="nav__menu__item--stock-market">Les dépenses</a>
				<a href="<?= RoutesHelper::Path("DisplayHome"); ?>" class="nav__menu__item--real-estate">Les plannings</a> -->
				<a href="<?= RoutesHelper::Path("DisplayContact"); ?>" class="nav__menu__item--contact">Contact</a>
<?php if (!UserHelper::IsLogin()): ?>
				<a href="<?= RoutesHelper::Path("AddUser"); ?>" class="nav__menu__item--user-account">Inscription</a>
				<a href="<?= RoutesHelper::Path("LoginUser"); ?>" class="nav__menu__item--user-account">Connexion</a>
<?php else: ?>
				<a href="<?= RoutesHelper::Path("LogoutUser"); ?>" class="nav__menu__item--user-account">Déconnexion</a>
<?php endif; ?>
			</section>
		</nav>
	</header>
	<main class="l-main main">
		<?php
			if (isset($this->content))
			{
				include($this->content);
			} 
		?>
	</main>
	<!-- <footer class="l-footer footer">
		<p class="footer__copyright">
			FamilyHub © Copyright 2023
		</p>
	</footer> -->
</body>
</html>