DROP DATABASE IF EXISTS familyhub;
CREATE DATABASE familyhub;

USE familyhub;

CREATE TABLE users
(
	id INT NOT NULL AUTO_INCREMENT
	, username VARCHAR(35) NOT NULL
	, email VARCHAR(100) UNIQUE NOT NULL
    , hash VARCHAR(100) NOT NULL
	, PRIMARY KEY (id)
)
ENGINE=InnoDB;